### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thecatalinstan** [kontaktio/appledoc-template#6]
Hi, 

I would like to use your template for one of my projects. There is, however, no license or hint thereof, associated with the project.  I realize it hasn’t been controbuted to in years and that you may not even be using it any longer, but you should know that it’s still relevant. Thanks for the great work 👍 

How would the MIT license work for you?

Thanks,
Cătălin

**Comment by stoprocent** [comment]
Just use it np. I will add license later
